Added support for multiple signatures
ninja-labs-tech/verify-pdf pull request #113
Opened 2021-02-27 15:32 UTC by gribera

Added support for multiple signatures

pd: sorry, I accidentally closed the other PR.

2021-03-01 20:23 UTC, MohammedEssehemy requested changes
Thank you for your contibution
let's check these points and when we finalize this PR, let's update README to show the new changes
Thank you

2021-03-01 20:23 UTC, MohammedEssehemy commented on lib/helpers/extractSignature.js
> +      pdfBuffer.slice(byteRanges[0][0], byteRanges[0][0] + byteRange[1]),
@gribera I think you meant `byteRange[0]` instead of `byteRanges[0][0]`

2021-03-01 20:23 UTC, MohammedEssehemy commented on lib/helpers/extractSignature.js
> +  const multiSignature = byteRanges.length - 1;
@gribera let's unify the output as an array even in a single signature case to be standard

2021-03-01 20:23 UTC, MohammedEssehemy commented on lib/testHelpers/test.data.js
> +  'signed-twice.pdf': [
@gribera if you have extra cases it will be better

2021-03-01 20:23 UTC, MohammedEssehemy commented on lib/verifyPDF.js
> +    return signaturesVerified;
@gribera I think the output should be similar to the single signature but with added property to show details of each signature, what do you think?

```
   {
      verified: false, // overall
      authenticity: false, // overall
      integrity: true, // overall
      expired: false, // overall
      signatures: [
          {
               verified: false,
               authenticity: false,
               integrity: true,
              expired: false
           },
          {
             verified: false,
             authenticity: false,
             integrity: true,
             expired: false
          }
        ]
    }

```

2021-03-02 17:28 UTC, gribera commented on lib/helpers/extractSignature.js
> +      pdfBuffer.slice(byteRanges[0][0], byteRanges[0][0] + byteRange[1]),
Yes! you are right, Always the first number of each ByteRange will be the beginning of the file. Fixed in https://github.com/ninja-labs-tech/verify-pdf/pull/113/commits/53872c9d70f604b1e43a5f1b08585dd152bc27e3

2021-03-02 17:40 UTC, gribera commented on lib/verifyPDF.js
> +    return signaturesVerified;
Ok, I think is a good idea. I unified the outputs like your example. 

Let me know if you want to change something

2021-03-02 17:44 UTC, gribera commented on lib/testHelpers/test.data.js
> +  'signed-twice.pdf': [
I'm looking for new pdf test documents signed multiple times.. in next commit I will add them and add some tests

2021-03-03 04:47 UTC, MohammedEssehemy requested changes

2021-03-03 04:47 UTC, MohammedEssehemy commented on lib/verifyPDF.js
> +      verified: !signatures.some(o => o.verified === false),
@gribera instead of `!` and `some`, have a look on [`every`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every)

2021-03-03 04:47 UTC, MohammedEssehemy commented on lib/testHelpers/test.data.js
> +    expired: true
@gribera can we add `signatures` prop also to the test

2021-03-03 04:47 UTC, MohammedEssehemy commented on lib/verifyPDF.js
>      for (let i = 0; i < signedData.length; i += 1) {
@gribera let's replace the for loop and pushing into the array with a [`map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

2021-03-03 04:47 UTC, MohammedEssehemy commented on lib/verifyPDF.js
> +    return signaturesVerified;
Amazing. Thank you

2021-03-04 00:41 UTC, gribera commented on lib/verifyPDF.js
>      for (let i = 0; i < signedData.length; i += 1) {
yes!, I tried the map function before, but the eslint threw an error on pre-commit

![image](https://user-images.githubusercontent.com/5048239/109885927-15d54300-7c5e-11eb-8fe7-de57775729b1.png)

Now, I put the map function again and skipped the verifications

2021-03-04 00:41 UTC, gribera commented on lib/testHelpers/test.data.js
> +    expired: true
added

2021-03-04 00:45 UTC, gribera commented on lib/testHelpers/test.data.js
> +  'signed-twice.pdf': [
Added a new test file with three signatures.

And a test case that checks the total signatures, please let me know if you agree with this test.

2021-03-04 00:45 UTC, gribera commented on lib/verifyPDF.js
> +      verified: !signatures.some(o => o.verified === false),
Sure!

2021-03-12 18:06 UTC, JulianAutogramm commented
Would love to see this feature merged soon, awesome work!

2021-04-20 16:22 UTC, pmartine commented
this functionality would be very helpful, great work!!

2022-05-26 18:32 UTC, merged